export const dataOfStudents = [
  {
    id: 1,
    name: "Keshav Chauhan",
    grade: 10,
    percentage: 84,
    sports: ["Cricket", "Chess"],
    careerChoices: ["Doctor", "Lawyer"],
    imgUrl: "https://picsum.photos/200/300?random=1",
  },
  {
    id: 2,
    name: "Raghav Singh",
    grade: 12,
    percentage: 95,
    sports: ["Tennis", "Chess"],
    careerChoices: ["Software Engineer", "Lawyer"],
    imgUrl: "https://picsum.photos/200/300?random=2",
  },
  {
    id: 3,
    name: "Preeti Sharma",
    grade: 11,
    percentage: 65,
    sports: ["Basket Ball", "Badminton"],
    careerChoices: ["Sound Engineer", "Singer"],
    imgUrl: "https://picsum.photos/200/300?random=3",
  },
  {
    id: 4,
    name: "Aditya Verma",
    grade: 10,
    percentage: 98,
    sports: ["Cricket", "Badminton"],
    careerChoices: ["Charted Accountant", "Singer"],
    imgUrl: "https://picsum.photos/200/300?random=4",
  },
  {
    id: 5,
    name: "Anjali Patel",
    grade: 12,
    percentage: 89,
    sports: ["Cricket", "Tennis", "Badminton"],
    careerChoices: ["Journalist", "Teacher"],
    imgUrl: "https://picsum.photos/200/300?random=5",
  },
  {
    id: 6,
    name: "Rahul Mehta",
    grade: 11,
    percentage: 92,
    sports: ["Chess", "Basket Ball"],
    careerChoices: ["Entrepreneur", "Politician"],
    imgUrl: "https://picsum.photos/200/300?random=6",
  },
  {
    id: 7,
    name: "Simran Gupta",
    grade: 10,
    percentage: 87,
    sports: ["Badminton", "Tennis"],
    careerChoices: ["Fashion Designer", "Archaeologist"],
    imgUrl: "https://picsum.photos/200/300?random=7",
  },
  {
    id: 8,
    name: "Vikram Singh",
    grade: 12,
    percentage: 78,
    sports: ["Cricket"],
    careerChoices: ["Pilot", "Athlete"],
    imgUrl: "https://picsum.photos/200/300?random=8",
  },
  {
    id: 9,
    name: "Neha Sharma",
    grade: 11,
    percentage: 91,
    sports: ["Chess", "Badminton", "Tennis"],
    careerChoices: ["Data Scientist", "Professor"],
    imgUrl: "https://picsum.photos/200/300?random=9",
  },
  {
    id: 10,
    name: "Aryan Patel",
    grade: 10,
    percentage: 83,
    sports: ["Cricket", "Basket Ball"],
    careerChoices: ["Graphic Designer", "Journalist"],
    imgUrl: "https://picsum.photos/200/300?random=10",
  },
  {
    id: 11,
    name: "Shreya Verma",
    grade: 12,
    percentage: 96,
    sports: ["Tennis"],
    careerChoices: ["Investment Banker", "Data Analyst"],
    imgUrl: "https://picsum.photos/200/300?random=11",
  },
  {
    id: 12,
    name: "Rohit Mehta",
    grade: 11,
    percentage: 88,
    sports: ["Cricket", "Chess", "Badminton"],
    careerChoices: ["Mechanical Engineer", "Businessman"],
    imgUrl: "https://picsum.photos/200/300?random=12",
  },
  {
    id: 13,
    name: "Priya Gupta",
    grade: 10,
    percentage: 94,
    sports: ["Basket Ball", "Tennis"],
    careerChoices: ["Psychologist", "Social Worker"],
    imgUrl: "https://picsum.photos/200/300?random=13",
  },
  {
    id: 14,
    name: "Ankit Singh",
    grade: 12,
    percentage: 90,
    sports: ["Cricket", "Badminton"],
    careerChoices: ["Civil Engineer", "Architect"],
    imgUrl: "https://picsum.photos/200/300?random=14",
  },
  {
    id: 15,
    name: "Megha Patel",
    grade: 11,
    percentage: 85,
    sports: ["Chess", "Tennis"],
    careerChoices: ["Dietitian", "Nutritionist"],
    imgUrl: "https://picsum.photos/200/300?random=15",
  },
  {
    id: 16,
    name: "Varun Sharma",
    grade: 10,
    percentage: 93,
    sports: ["Basket Ball", "Badminton", "Cricket"],
    careerChoices: ["Veterinarian", "Zoologist"],
    imgUrl: "https://picsum.photos/200/300?random=16",
  },
  {
    id: 17,
    name: "Sanjana Verma",
    grade: 12,
    percentage: 97,
    sports: ["Tennis", "Badminton"],
    careerChoices: ["Aerospace Engineer", "Astrophysicist"],
    imgUrl: "https://picsum.photos/200/300?random=17",
  },
  {
    id: 18,
    name: "Amit Mehta",
    grade: 11,
    percentage: 86,
    sports: ["Chess", "Cricket"],
    careerChoices: ["Pharmacist", "Biochemist"],
    imgUrl: "https://picsum.photos/200/300?random=18",
  },
  {
    id: 19,
    name: "Divya Gupta",
    grade: 10,
    percentage: 91,
    sports: ["Badminton", "Tennis", "Cricket"],
    careerChoices: ["Archaeologist", "Historian"],
    imgUrl: "https://picsum.photos/200/300?random=19",
  },
  {
    id: 20,
    name: "Rahul Singh",
    grade: 12,
    percentage: 88,
    sports: ["Basket Ball", "Tennis"],
    careerChoices: ["Electrical Engineer", "Robotics Engineer"],
    imgUrl: "https://picsum.photos/200/300?random=20",
  },
  {
    id: 21,
    name: "Pooja Patel",
    grade: 11,
    percentage: 95,
    sports: ["Cricket", "Chess"],
    careerChoices: ["Lawyer", "Judge"],
    imgUrl: "https://picsum.photos/200/300?random=21",
  },
  {
    id: 22,
    name: "Abhishek Sharma",
    grade: 10,
    percentage: 90,
    sports: ["Badminton", "Cricket", "Basket Ball"],
    careerChoices: ["Dentist", "Orthodontist"],
    imgUrl: "https://picsum.photos/200/300?random=22",
  },
  {
    id: 23,
    name: "Riya Verma",
    grade: 12,
    percentage: 93,
    sports: ["Tennis"],
    careerChoices: ["Chartered Accountant", "Financial Advisor"],
    imgUrl: "https://picsum.photos/200/300?random=23",
  },
  {
    id: 24,
    name: "Gaurav Mehta",
    grade: 11,
    percentage: 87,
    sports: ["Chess", "Badminton"],
    careerChoices: ["Neurologist", "Psychiatrist"],
    imgUrl: "https://picsum.photos/200/300?random=24",
  },
  {
    id: 25,
    name: "Neha Gupta",
    grade: 10,
    percentage: 92,
    sports: ["Basket Ball", "Tennis", "Cricket"],
    careerChoices: ["Meteorologist", "Geologist"],
    imgUrl: "https://picsum.photos/200/300?random=25",
  },
  {
    id: 26,
    name: "Arjun Singh",
    grade: 12,
    percentage: 89,
    sports: ["Cricket", "Badminton"],
    careerChoices: ["Chemical Engineer", "Materials Scientist"],
    imgUrl: "https://picsum.photos/200/300?random=26",
  },
  {
    id: 27,
    name: "Shreya Patel",
    grade: 11,
    percentage: 94,
    sports: ["Chess", "Tennis"],
    careerChoices: ["Economist", "Statistician"],
    imgUrl: "https://picsum.photos/200/300?random=27",
  },
  {
    id: 28,
    name: "Rohan Sharma",
    grade: 10,
    percentage: 91,
    sports: ["Badminton", "Cricket", "Basket Ball"],
    careerChoices: ["Radiologist", "Surgeon"],
    imgUrl: "https://picsum.photos/200/300?random=28",
  },
  {
    id: 29,
    name: "Aditi Verma",
    grade: 12,
    percentage: 96,
    sports: ["Tennis", "Badminton"],
    careerChoices: ["Marine Biologist", "Oceanographer"],
    imgUrl: "https://picsum.photos/200/300?random=29",
  },
  {
    id: 30,
    name: "Vivek Mehta",
    grade: 11,
    percentage: 88,
    sports: ["Chess", "Cricket"],
    careerChoices: ["Archaeologist", "Anthropologist"],
    imgUrl: "https://picsum.photos/200/300?random=30",
  },
];
